#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
~/.fehbg

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

bspc config border_width        2
bspc config window_gap          20

bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor -d ~ dev web gfx game #VI VII VIII IX X

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -r '*'

bspc rule -a Code desktop='^2'
bspc rule -a Steam desktop='^5' follow=on split_dir=right
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Opera desktop='^3'
bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a feh state=fullscreen
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a 'Emacs:emacs-everywhere' state=floating sticky=on
bspc rule -a '*:scratch' state=floating sticky=on border=off rectangle=1000x460+480+620
#bspc rule -a Screenkey manage=off

#xsetroot -cursor_name left_ptr &