# Hardware configuration for Artemis (DigitalOcean droplet)
# Generated by nixos-generate-config, cleaned up.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.loader.grub.device = "/dev/vda";
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi" ];
  boot.initrd.kernelModules = [ "nvme" ];

  fileSystems."/" = {
    device = "/dev/vda1";
    fsType = "ext4";
  };

  # No EFI partition on DO droplets (was a bogus autofs entry)
  # No swap partition (using zram instead)

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
