# kiss desk grid — BenQ primary. Missing displays are a no-op.
# See https://wiki.hyprland.org/Configuring/Monitors/
# hyprctl monitors all

$laptopM = desc:Sharp Corporation 0x14B8
$gamingM = desc:BNQ BenQ EX2710Q RBM07168019
$vertM   = desc:BNQ ZOWIE XL LCD LAG03858SL0
$topM    = desc:Lenovo Group Limited LEN X24A U3802912
#$crtM    = desc:???

#      0    720    1920   2560          4480     5560
# 0    +-----+             +-------------+
#      | CRT |             |             |
# 480  +-----+             |     Top     |
# 600                      |             +---------+
#                          |             |    V    |
# 1080              +------+-------------+    e    |
#                   |                    |    r    |
# 1440 +------------+                    |    t    |
#      |            |       Gaming       |    i    |
#      |   laptop   |                    |    c    |
#      |            |                    |    al   |
# 2520 +------------+--------------------+---------+

#       monitor   Resolution    x-y    scale  modifiers
monitor=$laptopM, 1920x1080@60, 0x1440,    1
monitor=$gamingM, 2560x1440@144, 1920x1080, 1
monitor=$topM,    1920x1080@144, 2560x0,    1
monitor=$vertM,   1920x1080@60, 4480x600,  1, transform, 3 # 1:90, 2:180, 3:270, 4:flipped
#monitor=$vertM,   1920x1080@60, 840x600,   1, transform, 3
#monitor=$crtM,      720x480@60, 0x0,       1

workspace=1, monitor:$gamingM, default:true
workspace=2, monitor:$gamingM
workspace=3, monitor:$gamingM
workspace=4, monitor:$vertM, layoutopt:orientation:top
workspace=5, monitor:$vertM, layoutopt:orientation:top
workspace=6, monitor:$vertM, layoutopt:orientation:top
workspace=7, monitor:$gamingM
workspace=8, monitor:$gamingM
workspace=9, monitor:$vertM, layoutopt:orientation:top
#workspace=10, monitor:$crtM
