#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg

bspc config border_width         5
bspc config window_gap          20

bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Steam desktop='^5' follow=on split_dir=right
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xsetroot -cursor_name left_ptr &
