#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
~/.fehbg

bspc config border_width        2
bspc config window_gap          20

bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor -d ~ dev web gfx game #VI VII VIII IX X

bspc rule -a Code desktop='^2'
bspc rule -a Steam desktop='^5' follow=on split_dir=right
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Opera desktop='^3'
#bspc rule -a Screenkey manage=off

#xsetroot -cursor_name left_ptr &
