#! /bin/sh

sxhkd &

bspc monitor DP-0 -d I II V VI
bspc monitor DVI-I-1 -d III IV VII VIII
bspc config border_width         2
bspc config window_gap          12

bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop='^5' follow=on split_dir=right
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
